# fly.toml app configuration file generated for markidown-svc on 2025-11-09T15:30:43+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'markidown-svc'
primary_region = 'fra'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 100
  processes = ['app']

[[http_service.checks]]
  grace_period = "10s"
  interval = "60s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[http_service.concurrency]
  type = "requests"
  soft_limit = 2
  hard_limit = 5

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
